[thinkingsoc_hackathon]
python.version = latest
is_custom = 1
label = ThinkingSOC_Hackathon
description = Send Splunk alert to ThinkingSOC backend (hackathon ingest API)
payload_format = json

param.url = http://127.0.0.1:9876/api/v1/alerts/splunk-ingest
