"""High-level SAIA SPL pipeline: generate → optimize → explain → validate."""

from __future__ import annotations

import logging
from typing import Any, Dict, Optional, Tuple

from config import Settings, mcp_configured
from models.analysis import RootCauseSpl
from services.llm.full_trace_log import log_saia_pipeline_start
from services.soc_analysis.soc_analysis_root_cause_spl import validate_root_cause_spl

from ..client import SplunkMcpClient
from ..errors import McpNotConfiguredError, McpToolError
from ..tool_registry import McpLogicalTool, resolve_tool_name
from .helpers import append_note
from .prompt import build_nl_query, build_saia_generate_args
from .tools import call_saia_explain, call_saia_generate, call_saia_optimize

logger = logging.getLogger(__name__)


async def generate_spl_via_mcp(
    settings: Settings,
    *,
    normalized: Optional[Dict[str, Any]] = None,
    search_name: Optional[str] = None,
    objective: Optional[str] = None,
    cim_schema_summary: str = "",
    datamodel: Optional[str] = None,
    index: Optional[str] = None,
    context: Optional[str] = None,
    query: Optional[str] = None,
) -> Tuple[Optional[RootCauseSpl], Dict[str, Any]]:
    """
    Full SAIA pipeline: generate → optimize → explain.

    Returns (RootCauseSpl or None, trace dict).
    """
    if not mcp_configured(settings):
        raise McpNotConfiguredError()
    client = SplunkMcpClient(settings)
    await client.ensure_ready()
    if not resolve_tool_name(client.tool_names, McpLogicalTool.SAIA_GENERATE_SPL):
        return None, {"error": "saia_generate_spl not available"}

    trace_query = query or build_nl_query(
        settings,
        normalized=normalized or {},
        search_name=search_name or context,
        objective=objective,
        cim_schema_summary=cim_schema_summary,
        datamodel=datamodel,
        index=index,
        context=context,
    )
    log_saia_pipeline_start(
        settings,
        query=trace_query,
        index=index,
        context=context or search_name,
        objective=objective,
    )
    trace: Dict[str, Any] = {"steps": []}
    saia_args = build_saia_generate_args(
        settings,
        normalized=normalized or {},
        search_name=search_name or context,
        objective=objective,
        cim_schema_summary=cim_schema_summary,
        datamodel=datamodel,
        index=index,
        context=context,
    )
    if getattr(settings, "tsoc_saia_llm_prepare_prompt", True):
        from services.investigation.saia_prompt_prepare import prepare_saia_prompt_with_llm

        prepared, ok = await prepare_saia_prompt_with_llm(
            settings,
            normalized=normalized or {},
            search_name=search_name or context,
            objective=objective,
            cim_schema_summary=cim_schema_summary,
            datamodel=datamodel,
        )
        if ok and prepared:
            saia_args["prompt"] = prepared
            trace["llm_prepare"] = {"ok": True, "prompt_chars": len(prepared)}
        else:
            trace["llm_prepare"] = {"ok": False}

    rc, gen_raw = await call_saia_generate(client, args=saia_args)
    trace["generate"] = gen_raw
    if rc is None:
        return None, trace

    if trace.get("llm_prepare", {}).get("ok"):
        append_note(rc, "llm_saia_prompt_prepared")

    if settings.tsoc_mcp_saia_optimize_spl:
        optimized = await call_saia_optimize(client, rc, search_name=context)
        trace["steps"].append("optimize" if optimized else "optimize_skipped")

    if settings.tsoc_mcp_saia_explain_spl:
        explained = await call_saia_explain(
            client, rc, search_name=context, objective=objective
        )
        trace["steps"].append("explain" if explained else "explain_skipped")
        if not explained and not rc.explanation:
            rc.explanation = (
                "SPL generated by Splunk AI Assistant (saia_generate_spl). "
                "Install or enable saia_explain_spl for a natural-language walkthrough."
            )

    from services.investigation.spl_tstats_sanitize import sanitize_spl_draft

    if rc.spl:
        rc.spl = sanitize_spl_draft(rc.spl)
    rc.validation = await validate_root_cause_spl(settings, rc, normalize_tstats=False)
    from services.investigation.spl_mcp_review import refine_root_cause_spl_until_valid, spl_validation_is_error

    if spl_validation_is_error(rc.validation):
        rc, _ = await refine_root_cause_spl_until_valid(
            settings,
            rc,
            normalized=normalized or {},
            search_name=search_name,
            objective=objective,
            cim_schema_summary=cim_schema_summary,
        )
    return rc, trace
